### PR TITLE
Add KraftKit configuration file for KraftCloud

### PR DESCRIPTION
**Pull request by razvand**
Add `kraft.cloud.yaml` configuration file to build and run for KraftCloud.

Build with:

```console
kraft build --kraftfile kraft.cloud.yaml
```

Run with:

```console
sudo kraft net create -n 172.44.0.1/24 kraft0
sudo kraft run --kraftfile kraft.cloud.yaml --network bridge:kraft0 --plat firecracker -a netdev.ipv4_addr=172.44.0.2 -a netdev.ipv4_gw_addr=172.44.0.1 -a netdev.ipv4_subnet_mask=255.255.255.0 -- helloworld
```

### CODE REVIEW

**Comment by craciunoiuc** [comment]
the libgo source will need to be changed before merging right?

**Comment by razvand** [comment]
> the libgo source will need to be changed before merging right?

@craciunoiuc , indeed. I changed this to a draft PR until [the corresponding `libgo` PR](https://github.com/unikraft/lib-libgo/pull/8) is merged.

**Review by StefanJum — CHANGES_REQUESTED** [review]
@razvand I get the following error when building with the command from the commit message:
```
<!> building kraftcloud-x86_64 (fc/x86_64)                                                                                                                                                                0% [1.2s]
 E  /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/.unikraft/build/Makefile:728: You did not choose any target platform.                                                                            
 E  /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/.unikraft/build/Makefile:729: *** Please choose at least one target platform in the configuration!.  Stop.                                       
 E  make[1]: *** [Makefile:1134: sub-make] Error 2  
 E  make: *** [Makefile:41: _all] Error 2  
```

**Comment by razvand** [comment]
> @razvand I get the following error when building with the command from the commit message:
> 
> ```
> <!> building kraftcloud-x86_64 (fc/x86_64)                                                                                                                                                                0% [1.2s]
>  E  /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/.unikraft/build/Makefile:728: You did not choose any target platform.                                                                            
>  E  /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/.unikraft/build/Makefile:729: *** Please choose at least one target platform in the configuration!.  Stop.                                       
>  E  make[1]: *** [Makefile:1134: sub-make] Error 2  
>  E  make: *** [Makefile:41: _all] Error 2  
> ```

Retry.

**Review by StefanJum — APPROVED** [review]
All good now, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by craciunoiuc — APPROVED** [review]
I remember that symbols like `CONFIG_LIBGO=y` are added automatically, but it's fine.

All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by razvand** [comment]
> I remember that symbols like `CONFIG_LIBGO=y` are added automatically, but it's fine.
> 
> All good here. Thanks!
> 
> Reviewed-by: Cezar Craciunoiu [cezar.craciunoiu@unikraft.io](mailto:cezar.craciunoiu@unikraft.io)

Lemme try to see whether I can leave some symbols out from the config file.

**Review by StefanJum — APPROVED** [review]
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Review by marcrittinghaus — APPROVED** [review]
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
